//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Belikov_IA
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Belikov_IAEntities : DbContext
    {
        public Belikov_IAEntities()
            : base("name=Belikov_IAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cleaning_Room> Cleaning_Room { get; set; }
        public virtual DbSet<Guests> Guests { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<payDay> payDay { get; set; }
        public virtual DbSet<Reservation> Reservation { get; set; }
        public virtual DbSet<room_acces> room_acces { get; set; }
        public virtual DbSet<Rooms> Rooms { get; set; }
        public virtual DbSet<C_Services> C_Services { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
